### ISSUE TITLE
Add onClose or onReadyStateChange event

### ISSUE THREAD

**Issue by ShaneMcC** [launchdarkly/okhttp-eventsource#12]
Would be useful to be able to detect when disconnects or reconnects happen.

**Comment by ShaneMcC** [comment]
As an addition to this (maybe a separate issue?) it would be nice to be able to provide a new URL to reconnect to.

(Use case: I'm using this library to interact with SignalR end points, and after disconnecting, the reconnect needs to pass a slightly-different URI to verify group membership top ensure the new connection continues to get the events it should)

**Comment by jkodumal** [comment]
Interesting use case-- sounds like a separate issue. It's not something that we've thought of, since it's not really part of the SSE standard, but if I remember correctly SignalR kind of deviates from that in places.

Would you be interested in contributing that functionality?

**Comment by ShaneMcC** [comment]
Thanks - I'll break that out as a separate issue - wasn't sure if you had a specific reason for ensuring the URI didn't change.

Happy to look to contribute the code myself, was just logging the issues first :)
