### ISSUE TITLE
HttpBasic Auth

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [launchdarkly/okhttp-eventsource#32]
Does this library offer support for HttpBasic authentication?

If not, would you accept a PR to add this functionality?

**Comment by eli-darkly** [comment]
Right now there are two ways you could configure EventSource to use basicauth:

1. Create an OkHttp client instance that's configured to use basicauth, as described in the OkHttp documentation, and then pass that instance to the `client` method of `EventSource.Builder`.

or 2. Compute the `Authorization` header yourself (i.e. set it to `Basic: HASH` where `HASH` is the base64 encoding of `username:password`) and pass that to the `headers` method of `EventSource.Builder`.

You're always welcome to submit a PR; whether it'd be accepted of course depends on the PR.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Oh sorry, didn't reply. thanks for your help, worked!
