### ISSUE TITLE
Default EventSources have a funny Logger Name

### ISSUE THREAD

**Issue by AdamRaken** [launchdarkly/okhttp-eventsource#34]
I had an issue yesterday where LaunchDarkly logs broke my Sematext logging.  By default the EventSource will have a name set to the Empty String - this is the default name for the builder, and it gets set on the EventSource when it is created. 

89:    this.name = builder.name;

This then gets put into the logger:

90:     this.logger = LoggerFactory.getLogger(EventSource.class.getCanonicalName() + "." + name);

Could I please suggest this:

    String loggerName = EventSource.class.getCanonicalName() +
      (!"".equals(name) ? "." + name : "");
    this.logger = LoggerFactory.getLogger(loggerName);

or a variation of it?  The name can never be null.  The . at the end of a Java class sent my Logstash Grok expressions into a loop and lost me my logs.  I have fixed the Grok regular expression to be more tolerant now :)

Many thanks!

**Comment by eli-darkly** [comment]
Sorry we missed this earlier. That's a reasonable fix.

**Comment by eli-darkly** [comment]
Fixed in 1.10.1.

**Comment by AdamRaken** [comment]
Super - thanks!
