### ISSUE TITLE
Bug: cleaning up threadpools does not work?

### ISSUE THREAD

**Issue by schleichardt** [launchdarkly/okhttp-eventsource#51]
I use Version 2.3.0 and when a connection error occurs and I want to shutdown the EventSource then the created threads (`okhttp-eventsource-stream-[]-0` and `okhttp-eventsource-events-[]-0`) are parked but not terminated. This is observable with [visualvm](https://visualvm.github.io/). Also more EventSources means more remaining threads that occupy resources.

I create the EventSource roughly like this:
```
EventSource.Builder(eventHandler, targetUri)
  .headers(headers)
  .client(httpClient)
  .connectionErrorHandler((e) -> ConnectionErrorHandler.Action.SHUTDOWN)
  .reconnectTime(ZERO)
  .build()
```

The cause is that in a [finally block](https://github.com/launchdarkly/okhttp-eventsource/blob/2.3.0/src/main/java/com/launchdarkly/eventsource/EventSource.java#L312-L319) the state is set to `SHUTDOWN` but when the [close method](https://github.com/launchdarkly/okhttp-eventsource/blob/2.3.0/src/main/java/com/launchdarkly/eventsource/EventSource.java#L192-L196) afterwards is called the threadpool termination is bypassed by the `return` statement as if the cleanup is already done.

My workaround for that issue is that I call the close method before the connectionErrorHandler returns.

Did I use the library wrong or is there certainly a bug?

**Comment by eli-darkly** [comment]
I think you're right - thanks for bringing this to our attention. I'm finding (as you probably did as well) that it's a bit annoying to follow the code paths in this section, and this is a good occasion for us to try to simplify them, which will help to keep this logic more correct in the future. I'm prioritizing this fix and will let you know if the patch is likely to be available soon, or if it ends up taking longer than I'm hoping.

**Comment by eli-darkly** [comment]
While adding a call to `close()` in this particular scenario does fix the thread issue, I found some related race conditions in how EventSource was managing state changes ("open" to "closed" vs. "shutdown", etc.), and ended up doing some much-needed cleanup as well as improving test coverage. We should have a patch out within a day or two.

**Comment by eli-darkly** [comment]
We've released the patch, but it's been taking a long time for the artifact to show up in Maven (as sometimes happens).

**Comment by eli-darkly** [comment]
2.3.1 should be available now, and the patch has also been integrated into the latest Java SDK release.
