### ISSUE TITLE
Dynamically update SSE URL in case of reconnect

### ISSUE THREAD

**Issue by Zaky7** [launchdarkly/okhttp-eventsource#61]
Hi, I want to thank you for the wonderful library.

I am having a use case where I subscribe to events over sse using an id `lastEventId` but my id is on URL params. 

I save lastEventId in my DB so that when I reconnect I would fetch events after it. 
 
How can I change the URL in case of reconnecting attempt so that I can use the latest eventId in URL params?

```kotlin
        val eventSource = EventSource.Builder(sseEventHandler, sseUrl)
            .method(method.toString())
            .headers(headers.build())
            .reconnectTime(reconnectTime)
            .build()
        eventSource.start()

```

**Comment by eli-darkly** [comment]
https://javadoc.io/static/com.launchdarkly/okhttp-eventsource/2.3.2/com/launchdarkly/eventsource/EventSource.Builder.html#lastEventId-java.lang.String-

**Comment by Zaky7** [comment]
thanks, @eli-darkly but the vendor I am connecting uses lastEventId in params instead of the Id field of the SSE protocol.

like this

`https://text.sandbox?since_id=<lastEventId>` 

how can I achieve this? one possible solution in my mind is to call eventsource.close on an error and then again start a new connection with updated lastEventId in URL.

**Comment by eli-darkly** [comment]
> one possible solution in my mind is to call eventsource.close on an error and then again start a new connection with updated lastEventId in URL

That's the only way you can do it with this library. It was not designed for dynamically changing the URL on an automatic reconnect.

**Comment by Zaky7** [comment]
@eli-darkly what if i pass custom okHttpClient and add interceptor for updating URL on reconnect would that work?

**Comment by eli-darkly** [comment]
I can only suggest that you try it and see if it works for you. What you're proposing isn't something we have needed to do in our use cases, and therefore we haven't tried doing it.

**Comment by Zaky7** [comment]
![Screenshot 2021-12-17 at 5 11 03 PM](https://user-images.githubusercontent.com/16975648/146539534-de00c080-9651-4b02-b26e-5c337e12b7ce.png)


I think event Okhttp says that
