### ISSUE TITLE
how to add security token?

### ISSUE THREAD

**Issue by rwst** [launchdarkly/okhttp-eventsource#67]
How would I add a security token to the GET request? As you are using okhttp can I somehow use an interface like
```
    interface BoardGameStreamApi {
        @Streaming
        @GET("/api/board/game/stream/{gameId}")
        suspend fun boardGameStream(
            @Header("Authorization") token: String,
            @Path("gameId") gameId: String
            ): Response<List<ServerSideEvent>>
    }
```
as start to access the event source? I could try to add this but I need your feedback about if this is doable.

Thanks,

**Comment by eli-darkly** [comment]
If this is just a matter of adding an `Authorization` header, then what you want is [`EventSource.Builder.headers`](https://javadoc.io/doc/com.launchdarkly/okhttp-eventsource/latest/com/launchdarkly/eventsource/EventSource.Builder.html).

There isn't any way to directly use a web service interface like you suggested. We use OkHttp at a low level to do basic HTTP request stuff— you would have to do the rest (like, adding the path parameter into the URL) yourself.

**Comment by rwst** [comment]
I see, I should have looked longer at the code. Thanks.
