### ISSUE TITLE
Make SSE reconnect strategy configurable, with backoff and jitter

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/okhttp-eventsource#7]
See launchdarkly/java-client#74 for background.

**Comment by samhaldane** [comment]
Thanks John. Do you have an ETA on this?

**Comment by jkodumal** [comment]
Hi @samhaldane -- I'm working on this now. We should have a release in the next few days.

**Comment by samhaldane** [comment]
Sounds good.

**Comment by jkodumal** [comment]
This was fixed in 0.2.3.
