### ISSUE TITLE
I can't open the doc website http://javadoc.io/doc/com.launchdarkly/okhttp-eventsource

### ISSUE THREAD

**Issue by king-ma1993** [launchdarkly/okhttp-eventsource#90]
![image](https://github.com/launchdarkly/okhttp-eventsource/assets/77381352/6418f6a5-de3f-47ae-af91-622f812cb328)

**Comment by tanderson-ld** [comment]
It appears the javadoc.io outage is resolved.

**Comment by tanderson-ld** [comment]
An alternative location for docs: https://launchdarkly.github.io/okhttp-eventsource/
